# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7287981c52b0862d6d3e9c42795ccbed"
name = "shipping-date-picker"
handle = "shipping-date-picker-2"
application_url = "https://legendary-rn-consortium-mongolia.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://legendary-rn-consortium-mongolia.trycloudflare.com/auth/callback",
  "https://legendary-rn-consortium-mongolia.trycloudflare.com/auth/shopify/callback",
  "https://legendary-rn-consortium-mongolia.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
